moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - robot1_shoulder_pan_joint
      - robot1_shoulder_lift_joint
      - robot1_elbow_joint
      - robot1_wrist_1_joint
      - robot1_wrist_2_joint
      - robot1_wrist_3_joint
